language: node_js
sudo: false
notifications:
  email: false
scripts:
  - lhci autorun

# dependencies of lhci:
addons:
  chrome: stable
before_install:
  - npm install -g @lhci/cli@0.7.x

before_script:
  - git remote set-branches --add origin 4.0.0
  - git fetch
